import { Button } from "std-widgets.slint";


export component SplashScreen inherits Window {

    no-frame: true;
    width: 600px;
    height: 300px;
    callback splash-button-pressed <=> btn.clicked;

    background: #1e1e1e;
    VerticalLayout {
        Text {
            horizontal-alignment: center;
            text: "Welcome to cfg-watcher!";
            font-family: "JetBrains Mono";
            font-size: 24px;
            font-weight: 900;
        }

        HorizontalLayout {
            Rectangle {
                height: 50px;
            }

            btn := Button {
                text: "Take me there!";
                width: 200px;
                height: 50px;
                clicked => {}
            }

            Rectangle { }
        }

        Rectangle { }
    }
}
